
blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/ngageoint/coordinate-reference-systems-ios/discussions
    about: Questions, Feature Requests, Feedback, Conversations
